<?xml version="1.0" encoding="utf-8"?><Database Name="CICO" Class="CICOModelsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=CICO;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CICOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[_User]" Member="_Users">
    <Type Name="_User">
      <Column Name="IdUser" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CalloriesRequirements" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Aliment" Member="Aliments">
    <Type Name="Aliment">
      <Column Name="IdAliment" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Aliment_Journal" Member="Journals" ThisKey="IdAliment" OtherKey="IdAliment" Type="Journal" />
    </Type>
  </Table>
  <Table Name="dbo.Journal" Member="Journals">
    <Type Name="Journal">
      <Column Name="IdJournal" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdAliment" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="MealName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CalloriesAmount" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="Aliment_Journal" Member="Aliment" ThisKey="IdAliment" OtherKey="IdAliment" Type="Aliment" IsForeignKey="true" />
    </Type>
  </Table>
</Database>